[[language]]
name = "python"
language-servers = [ "pyright", "ruff" ]
auto-format = true
formatter = {command="ruff", args = ["format","-"]}

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"

[language-server.ruff]
command = "ruff-lsp"

[[language]]
name = "zig"
language-servers = ["zls"]

[language-servers.zls]
command = "zls"
